// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO ai_conversation_turns (
    id,
    conversation_id,
    turn_number,
    agent,
    role,
    content,
    parts,
    model,
    provider,
    timestamp
)
SELECT
    gen_random_uuid(),
    c.id,
    COALESCE((SELECT MAX(turn_number) FROM ai_conversation_turns WHERE conversation_id = c.id), 0) + 1,
    'crush-rcm',
    $2,
    $3,
    $3::jsonb,
    $4,
    $5,
    CURRENT_TIMESTAMP
FROM ai_conversations c
WHERE c.session_id = $1
RETURNING id, conversation_id, role, parts, model, timestamp, created_at, finished_at, provider
`

type CreateMessageParams struct {
	ID        string         `json:"id"`
	SessionID string         `json:"session_id"`
	Role      string         `json:"role"`
	Parts     string         `json:"parts"`
	Model     sql.NullString `json:"model"`
	Provider  sql.NullString `json:"provider"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.queryRow(ctx, q.createMessageStmt, createMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.Parts,
		arg.Model,
		arg.Provider,
	)
	var i Message
	var convID sql.NullString
	var timestamp, createdAt sql.NullTime
	err := row.Scan(
		&i.ID,
		&convID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&timestamp,
		&createdAt,
		&i.FinishedAt,
		&i.Provider,
	)
	i.SessionID = arg.SessionID
	if timestamp.Valid {
		i.CreatedAt = timestamp.Time.Unix()
		i.UpdatedAt = i.CreatedAt
	}
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM ai_conversation_turns
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteMessageStmt, deleteMessage, id)
	return err
}

const deleteSessionMessages = `-- name: DeleteSessionMessages :exec
DELETE FROM ai_conversation_turns t
USING ai_conversations c
WHERE t.conversation_id = c.id
AND c.session_id = $1
`

func (q *Queries) DeleteSessionMessages(ctx context.Context, sessionID string) error {
	_, err := q.exec(ctx, q.deleteSessionMessagesStmt, deleteSessionMessages, sessionID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, role, parts, model, created_at, finished_at, provider
FROM ai_conversation_turns
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.queryRow(ctx, q.getMessageStmt, getMessage, id)
	var i Message
	var convID sql.NullString
	var createdAt sql.NullTime
	err := row.Scan(
		&i.ID,
		&convID,
		&i.Role,
		&i.Parts,
		&i.Model,
		&createdAt,
		&i.FinishedAt,
		&i.Provider,
	)
	if createdAt.Valid {
		i.CreatedAt = createdAt.Time.Unix()
		i.UpdatedAt = i.CreatedAt
	}
	return i, err
}

const listMessagesBySession = `-- name: ListMessagesBySession :many
SELECT t.id, c.session_id, t.role, t.parts, t.model, t.created_at, t.created_at, t.finished_at, t.provider
FROM ai_conversation_turns t
JOIN ai_conversations c ON t.conversation_id = c.id
WHERE c.session_id = $1
ORDER BY t.turn_number ASC
`

func (q *Queries) ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.query(ctx, q.listMessagesBySessionStmt, listMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Parts,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET
    parts = ?,
    finished_at = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateMessageParams struct {
	Parts      string        `json:"parts"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.exec(ctx, q.updateMessageStmt, updateMessage, arg.Parts, arg.FinishedAt, arg.ID)
	return err
}
